-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 14:12:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema antojitos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema antojitos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `antojitos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `antojitos` ;

-- -----------------------------------------------------
-- Table `antojitos`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antojitos`.`pagos` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `tipo_pago` VARCHAR(35) NOT NULL,
  `descripcion_pago` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pago`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
